AUBGTheHUB/monolith

- packages/web/src/components/spa/HackAUBG/HackAUBG.jsx
- packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx
- packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx
- packages/web/src/components/spa/Navigation/MobileNav/mobile_navbar.css
- packages/web/src/components/spa/Navigation/NavFactory.js
Added hover props for both mobile and desktop nav. Now almost everything is customizable. e.g. background color of both navs, sticky position of desktop nav, anchor colors when mobile or desktop and respectively hover color as well.
> #228 #230 Add hover props

- packages/api/tests/hackathon_teams_test.go
- packages/api/tests/utils.go
Adds a cleanup which drops the test collection and makes sure there are no leftover document entries in the DB after running the tests. This ensures we can create entries with the same data and don't get bad request responses from the API.
> Add cleanup for _tests collection

- packages/api/controllers/hackathon_register_controller.go
- packages/web/src/feature_switches.js
Removed unnecessary code from hackathon registration controller. The removed code was initially used for dummy testing of the registration email confirmation on a single email account. This code should have been removed immediately after the completion of the personalized user testing results.
> #447 removed unnecessary testing code from hackathon registration controller

- .github/CODEOWNERS
- packages/web/src/App.js
- packages/web/src/Global.js
- packages/web/src/components/admin_page/dash_page.jsx
resolves #98 
Manually append `/actions` to an endpoint of section you've chosen from the dashboard.
For example `partners` which lives on `/admin/dashboard/partners`
Try to access `/admin/dashboard/partners/actions` and you should be returned back to the previous page no matter whether you do it in the same tab or in a new one.
> #98 Drop actions endpoint if stateless

- packages/py-api/py_api/controllers/url_shortener_controller.py
- packages/py-api/py_api/utilities/parsers.py
Do not allow the creation of invalid shortened urls which result in 404 when trying to be reached, updated or removed.
* Try to create a bad endpoint including any one of the prohibited characters. You should get a 400 response or a message on the frontend saying that your input includes a prohibited character.
* Try to break it
resolves #488
> #488 Fix upsert request in shortener to not allow bad endpoints

- packages/py-api/py_api/utilities/logging.py
Fixed the issue with not showing messages of log-level INFO and not formatting the ones from level WARNING and above by overwriting uvicorn's default logging config.
resolves #494
> #494 Resolve issue with not showing messages of loglevel INFO

- .env.sample
- packages/py-api/py_api/environment.py
- packages/py-api/py_api/main.py
- packages/py-api/py_api/middleware/__init__.py
- packages/py-api/py_api/middleware/analytics.py
- packages/py-api/py_api/middleware/auth.py
- packages/py-api/py_api/middleware/exception_handler.py
- packages/py-api/py_api/middleware/middleware.py
Created a middleware for running a background task for updating a document in the database representing the total count of requests made to the server.
The document looks as follows:
How to verify:
resolves #498
> #498 Add basic request analytics

- packages/api/app/app.go
- packages/api/configs/cors.go
- packages/py-api/py_api/main.py
- packages/py-api/py_api/middleware/auth.py
- packages/py-api/py_api/utilities/cors.py
Allow all localhost aliases with ports 3000, 3001, 6969, https://thehub-aubg.com and https://dev.thehub-aubg.com as origins.
resolves #503
> #503 Set up proper CORS origins

- Makefile
- cli.sh
- nginx/Dockerfile
- nginx/docker-compose.yml
- nginx/nginx.conf
- packages/api/configs/cors.go
- packages/py-api/py_api/utilities/cors.py
- packages/web/package.json
- packages/web/public/index.html
Reverse proxy POC is accepted but moving to Svelte is still being discussed. Updated the PR to include only the reverse proxy changes which will help developers set up proper requests since it's imitating how requests are being proxied on deployed environments.
In order to be able to run Svelte as the main frontend and still have access to the react admin panel, we have to place all services behind a reverse proxy.
How to test the POC:
If we decide to proceed with using Svelte, we would need to double down on cleaning up all redundant code from the admin panel. Additionally, we will need to drop all current svelte files and generate a new empty project.
> Nginx reverse proxy for local development

- packages/services/questionnaire/src/routes/questionnaires/[department]/+page.svelte
Edited width property because text was not being displayed properly
> Fix mobile width because text is cut at the end

- manage_app.py
Removed the "\n" character from the name of the branch because it was causing 
We will have to see if this really fixes the problem
Fix #550
> #550 Remove new line from branch name

- packages/py-api/py_api/controllers/questionnaires_controller.py
Added a new column called "Submission time" to the CSV export so that we could compare the timestamps of creation more easily
> Added submission times to the csv export from MongoDB

- deployment.sh
The expected status code of the shortener should be 301, not 302
> Change expected status code of shortener from 302 to 301

- packages/py-api/py_api/controllers/hackathon_participants_controller.py
#589 Add a check for put request if the participant does not exist
I enclosed the find_and_update method call within a try-catch block to check for an invalid objectID type. Moreover, if the objectID is correct I check if that participant exists.
> Added check when updating participant

- packages/py-api/py_api/controllers/hackathon/participants_controller.py
- packages/py-api/py_api/functionality/hackathon/participants_base.py
- packages/py-api/py_api/functionality/hackathon/teams_base.py
Implemented the logic of adding a random participant. If there is enough space, the participant is added to an available existing random team, otherwise, if there is space a new random team is created with this participant as the admin.
> #615 Implements the logic of creating a new participant

- packages/py-api/py_api/controllers/hackathon/participants_controller.py
- packages/py-api/py_api/functionality/hackathon/participants_base.py
- packages/py-api/py_api/functionality/hackathon/teams_base.py
Refactored the block located in the add_participant function which deals with the creation and addition of a new random participant to either an existing random team or a new random team if there are any spaces. What I did is I created two separate functions for the possible scenarios and applied the existing logic in both of them. 
Additionally, I removed some unused imports from the teams_base file.
> 669 refactors random participant creation block

- packages/py-api/py_api/controllers/hackathon/participants_controller.py
- packages/py-api/py_api/controllers/hackathon/verification_controller.py
- packages/py-api/py_api/functionality/hackathon/teams_base.py
I added a background task in the verification controller to send an email to the verified random participant and modified the message sent to the admin of a normal team to also include a successful registration message. Furthermore, for the participants who are registered by link, the logic for sending the email is implemented in the participant's controller in the method named add_participant_to_existing_team(), because they are verified by default and they dont use the verify endpoint. I also changed some confusing logic about how the check for the capacity reach was made in the add_participant method to something that I think is more clear and correct. The previous version wasn't letting you add a participant to an existing team when the number of teams had reached the cap. This was …
> 662 Implements sending successful registration messages to participants

- packages/py-api/py_api/controllers/hackathon/participants_controller.py
- packages/py-api/py_api/controllers/hackathon/verification_controller.py
- packages/py-api/py_api/database/database_transaction_handlers.py
- packages/py-api/py_api/database/initialize.py
- packages/py-api/py_api/environment.py
- packages/py-api/py_api/functionality/hackathon/jwt_base.py
- packages/py-api/py_api/functionality/hackathon/participants_base.py
- packages/py-api/py_api/functionality/hackathon/teams_base.py
- packages/py-api/py_api/middleware/auth.py
- packages/py-api/py_api/models/hackathon_participants_models.py
- packages/py-api/py_api/routes/hackathon/verification_routes.py
- packages/web/src/components/spa/HackAUBG/VerifyAccountPop/VerifyAccount.jsx
* Now teams are created only when the participant verifies their email
* Random participants are added to existing random teams on email verification
* There are no more admins of random teams as it was confusing.
* The logic for creating a participant via an invite link stays the same.
* Changed method for the verify endpoint from `GET `to `POST`
> Add participants to team on email verification

- services/py-api/src/database/model/participant_model.py
- services/py-api/src/database/model/team_model.py
#Quick fix
The methods in the serializing methods in the participant and team models did not include the timestamps when building JSON object and the mongoDB document. The base model correctly generated by default a timestamp and an objectID, however we were not using them.
> Save the timestamps in the database

- services/py-api/src/database/db_manager.py
- services/py-api/src/database/repository/participants_repository.py
- services/py-api/src/database/repository/teams_repository.py
- services/py-api/src/database/transaction_manager.py
- services/py-api/tests/unit_tests/conftest.py
- services/py-api/tests/unit_tests/test_database_layer/test_db_manager.py
- services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py
- services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py
- services/py-api/tests/unit_tests/test_database_layer/test_trancation_manager.py
#747 Add retrying of UnknownTransactionCommitResult Error
It is done in the same fashion as the _retry_tx is done using exponential backoff for retrying. However, it does not return a result.OK object since commit_transaction does not return anything
resolves #747
> #747 Add retry logic to commit_transaction

- services/py-api/src/database/transaction_manager.py
- services/py-api/src/server/config/server_config.py
- services/py-api/src/server/logger/logger_factory.py
#762 Writes the exception traceback in the logfile for PROD and DEV environments
We were using conflicting processors for structlog, this caused the issue of the exception not being printed in the file. Moreover, I noticed a weird behaviour with the way the .env file is interpreted by load_dotenv in my machine. It seems like it was using some sort of caching system to make the reading of the env variables faster and it was not listening to new changes I was making in the .env. I literally deleted the .env file and the app was still running. To solve this issue I read a little more about load_dotenv works, which you can check on the picture below: 
Apparently, if you do not specify a value for override it defaults to False, which means that the function will first look for the value of …
> #762 Write the exception traceback in the logfile

- services/py-api/src/service/participants_service.py
> Invoke functions and retreive constants form the object of TeamsRepository

- services/py-api/src/database/model/participant_model.py
- services/py-api/src/database/repository/participants_repository.py
- services/py-api/src/database/repository/teams_repository.py
- services/py-api/src/server/exception.py
- services/py-api/src/server/handlers/verification_handlers.py
- services/py-api/src/server/routes/routes.py
- services/py-api/src/server/routes/verification_routes.py
- services/py-api/src/server/schemas/jwt_schemas/jwt_user_data_schema.py
- services/py-api/src/server/schemas/jwt_schemas/schemas.py
- services/py-api/src/server/schemas/request_schemas/schemas.py
- services/py-api/src/server/schemas/response_schemas/schemas.py
- services/py-api/src/service/hackathon_service.py
- services/py-api/src/service/participants_registration_service.py
- services/py-api/src/service/participants_verification_service.py
- services/py-api/src/utils.py
- services/py-api/tests/integration_tests/conftest.py
- services/py-api/tests/integration_tests/test_jwt_utility.py
- services/py-api/tests/integration_tests/test_participant_routes.py
- services/py-api/tests/integration_tests/test_verification_routes.py
- services/py-api/tests/unit_tests/conftest.py
- services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py
- services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py
- services/py-api/tests/unit_tests/test_handlers/test_verification_handlers.py
- services/py-api/tests/unit_tests/test_service_layer/test_hackathon_service.py
- services/py-api/tests/unit_tests/test_service_layer/test_participant_registration_service.py
#808 verify random participant flow
@Alexandr-Ignatov did a great job implmenting the logic of the verification of the random participant. Due to structural changes that @IvanObreshkov and I did to the project, I had to do some refactoring and restructuring of things. 
Now we use a model to update the participant document called `UpdatedParticipant` which you can dump using `dump_model`. All the fields of this model are optional and `dump_model` will hide any field that is unset. This way you can use it to update the participant document using the method find_one_and_update().
We were previously relying on a single JWT schema that was inefficient because it included extra fields both in the verification and registration of the participant. I split the schema into 2 cases and updated the …
> #808 verify random participant flow

- services/py-api/src/database/db_manager.py
- services/py-api/tests/unit_tests/conftest.py
- services/py-api/tests/unit_tests/test_handlers/test_utility_handlers.py
- services/py-api/tests/unit_tests/test_service_layer/test_participant_registration_service.py
We were having issues with integration tests not passing due to other existing documents on the DEV database that were clashing/interfering with the tests. To address this issue we created a separate TESTS database for the test environment.
> Switch db based on env

- services/web/src/website/MainPage/MeetTheTeamSection/components/HubberModule.tsx
#922 Implements ellipses on hover and reworks the size dimensions for different devices
Had to rework, the sizes of tiles and images, because otherwise it would either crop the image or would not display the full name on touch-screen devices.
Now it works on devices and it has an effect on hover
> 922 Implements ellipses on hover and reworks the size dimensions for different devices

- services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx
#954 Fix Registration Page Resending Email Issue
Updated Toast Styling and Resend Email Conditions
I adjusted the resend email functionality to only show when it's appropriate, not under the 'invite_link' registration type. I've also updated the toast notification styles to fit our dark theme better.
resolves #954
> 954 Fix Registration Page Resending Email Issue
