packages/web/src/App.js, packages/web/src/components/admin_page/admin.css, packages/web/src/components/admin_page/dash_page.jsx, packages/web/src/components/admin_page/landing_admin_page.jsx, packages/web/src/components/admin_page/members.jsx, packages/web/src/components/admin_page/members_page/members.jsx, packages/web/src/components/admin_page/members_page/new_member.jsx, packages/web/src/components/admin_page/members_page/render_members.jsx, packages/web/src/components/admin_page/members_page/single_member.jsx, packages/web/src/components/admin_page/render_members.jsx, packages/web/src/index.js
GET, POST, DELETE, PUT with auth_token and prop passing for storing current set of members
=> Add all member functionalities

packages/web/src/Global.js
This PR adds a conditional statements which swaps the value of the url depending on what is the environment. By doing so there is no need for us to change manually urls when deploying.
=> #43 use NODE_ENV for checking env and swapping url

packages/api/configs/cron.go, packages/api/configs/env.go, packages/api/go.mod, packages/api/go.sum, packages/api/main.go
Created a function that generates a random string with a fixed length (I have used 32 characters but it can be changed by adding a different parameter to the function). Also created a cron job that sets a new random value of the BEARER TOKEN every 24 hours.
=> #53 daily generation of authentication token

packages/web/src/components/admin_page/admin.css, packages/web/src/components/admin_page/dash_page.jsx
=> #56 Changed color and fix responsiveness of management panel

packages/web/src/components/admin_page/admin.css
Reverts AUBGTheHUB/spa-website-2022#66
=> Revert "#65-form-fields-no-longer-turn-white-when-clicked"

packages/web/src/components/admin_page/admin.css
This reverts commit 1c6bedc5794568dfa4c657dfa7136f94e909752e.
=> Revert "#65-action-page-fields-are-darker-when-clicked"

data/certs/.gitignore, manage_app.py
Added a CRON job for generating new certificates and triggering a redeploy.
=> #75 CRON job for restarting services with newly generated SSL/TLS certificates

packages/web/nginx.conf
Redirected the traffic to the HTTPS version of the website.
=> Made https redirecting

.github/CODEOWNERS
#63  Added @IvanObreshkov as a CODEOWNER of nginx.conf file
=> #63 Added @IvanObreshkov as a CODEOWNER of nginx.conf file

.githooks/pre-commit
I've made the hooks skip the linting process if there are no js derivative files
=> #25 Optimized git hooks

packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx, packages/web/src/components/spa/Navigation/MobileNav/style.css
Added HackAUBG button and redirection to /hackaubg.
=> #92 HackAUBG button in hamburger menu

packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx, packages/web/src/components/spa/Navigation/MobileNav/style.css
Added new width and heights to the nav buttons and logo. Changed "the hub" `paragraph` property to h2.
=> #86 fixed button and the hub text sizing

packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx, packages/web/src/components/spa/Navigation/DesktopNav/desktop_navbar.css
#88 Added on-click button rerouting to the HackAUBG button in desktop and changed button design
=> #88 hack aubg button design and rerouting

packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx, packages/web/src/components/spa/Navigation/MobileNav/style.css
Changed the sizing of the x button from px to % so that it is more responsive. Issue:#86
=> #86 fixed the size of the close hamburger button

packages/web/src/components/spa/Navigation/DesktopNav/desktop_navbar.css
#113 Fixed button spacing and the text break of HackAUBG button
=> #113 Fixed button spacing and HackAUBG text break

packages/web/src/components/spa/Welcome_section/Welcome.jsx, packages/web/src/components/spa/landing_home_page.jsx
WORKING ISSUE: #101 Welcome to the Hub Section
Created the welcome_section folder containing files: Welcome.jsx and welcome_section.css
=> #101 Created welcome_section folder and added jsx and css files

packages/web/src/Global.js, packages/web/src/components/spa/Members/Members.jsx
Remove the need for environment variables when trying to make requests towards the api in different environments
=> #126 New logic for origin url

packages/web/src/App.css, packages/web/src/components/spa/MainPage.jsx, packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx, packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx, packages/web/src/components/spa/Navigation/NavBar.jsx, packages/web/src/components/spa/Navigation/NavFactory.js
Navbar now accepts a Props object which is constructed from `anchorList : Array<Anchor>` and `hasHackButton : boolean`. Has conditional rendering for HackAUBG button
=> #140 Refactor Navbar for reusability

packages/web/src/components/admin_page/admin.css
Added min-height property to the admin page. issue:#97
=> #97 add min-height property to admin panel 

packages/web/src/components/admin_page/admin.css, packages/web/src/components/admin_page/events_page/actions_events.jsx, packages/web/src/components/admin_page/events_page/add_event.jsx
#128 changed start/end date input fields. Added conversion to ISOstring for the new input fields to both add and actions page and added a check if the end data is before start date.
=> #128 management panel for events to work with datetime local input fields

packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx
Fix bug where nav wasn't expending to the page's height when an anchor is clicked
=> #169 Fixed nav expanding

packages/web/src/components/spa/LandingSection/landing_section.css, packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx, packages/web/src/components/spa/Navigation/MobileNav/mobile_navbar.css
=> #169 text animation is sometimes visible when opening the hamburger menu and then disappears

packages/web/src/components/spa/Navigation/DesktopNav/desktop_navbar.css, packages/web/src/components/spa/Navigation/MobileNav/mobile_navbar.css
#173 - Changed the gradient for the HackAUBG button
=> #173 hack aubg change button gradient

packages/web/src/components/spa/HackAUBG/AboutHackathon/AboutHackathon.jsx, packages/web/src/components/spa/HackAUBG/AboutHackathon/about_hackathon.css, packages/web/src/components/spa/HackAUBG/HackAUBG.jsx
=> #174 hack aubg about us section

packages/web/src/components/spa/Footer/Footer.jsx, packages/web/src/components/spa/HackAUBG/HackAUBG.jsx, packages/web/src/components/spa/MainPage.jsx
Added props functionality to the Footer component. Changed Footer colour, depending on the page.
=> #184 Add HackAUBG footer and props

packages/web/src/components/spa/MainPage.jsx, packages/web/src/components/spa/MembersSection/MembersCard.jsx, packages/web/src/components/spa/MembersSection/MembersSection.jsx, packages/web/src/components/spa/MembersSection/members.css
Reverts AUBGTheHUB/spa-website-2022#214
=> Revert "#210 Fix members carousel responsiveness"

packages/web/src/components/spa/HackAUBG/HackAUBG.jsx, packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx
1. Go to branch, run web
2. Open localhost in mobile resolution
3. Try to go to HackAUBG using the mobile nav
If you can scroll down, this fix is working -> approve PR
=> #226 fix blocked scrolling behaviour in HackAUBG

packages/web/src/components/spa/Navigation/DesktopNav/desktop_navbar.css
#229 Added css for making the mouse as pointer while onHover the Hub logo
=> #229 fixed mouse pointer while on hover for hub logo

packages/web/src/components/other/page_not_found.css
Fixed scaling issues and logo scaling by changing width from % to vh/vw.
=> #243 qa 404 page issues to be resolved

packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/journey_desktop.css
Added more clarification when using the css so that there isn't css in the wrong place
=> #268 Fix Hub Members right arrow

.github/workflows/discord.yml
Sends a notification to `#github` channel in discord whenever a new PR is opened
=> Add Discord workflow

packages/api/controllers/partners_controller.go, packages/api/controllers/sponsors_controller.go, packages/api/models/hackathon_team_member_model.go, packages/api/models/sponsors_partners_models.go, packages/web/src/App.js, packages/web/src/components/admin_page/hackathon/hackathon_partners/actions_partners.jsx, packages/web/src/components/admin_page/hackathon/hackathon_partners/add_partners.jsx, packages/web/src/components/admin_page/hackathon/hackathon_partners/render_partners.jsx, packages/web/src/components/admin_page/hackathon/hackathon_sponsors/actions_sponsors.jsx, packages/web/src/components/admin_page/hackathon/hackathon_sponsors/add_sponsors.jsx, packages/web/src/components/admin_page/hackathon/hackathon_sponsors/render_sponsors.jsx
@SuelaCark  @nikolayninov I don't know if the business logic requires for partners to have a category field as well. LMK if I need to remove it.
=> #265 Add category field for Sponsors and Partners

packages/web/src/components/spa/HackAUBG/LandingAnimation/landing_animation.css, packages/web/src/components/spa/Navigation/MobileNav/mobile_navbar.css
I added padding-top to fix the issue for animation section being cropped by the hamburger menu.
Also, I changed the vh for both mobile and desktop. If you think that a particular size for the animation responsiveness is not looking good, just lmk.
=> #297 fixed vh for both mobile and desktop animation

packages/web/src/Global.js, packages/web/src/components/spa/Footer/Footer.jsx, packages/web/src/components/spa/Footer/footer.css, packages/web/src/components/spa/HackAUBG/HackAUBG.jsx, packages/web/src/components/spa/MainPage.jsx
Added spans to all icons and remade borders
=> #295 footer icons issue on mobile devices

packages/web/src/components/spa/Footer/Footer.jsx, packages/web/src/components/spa/Footer/footer.css
Changes the background and border radius property location
=> #302 fix footer icons roundening

.vscode/tasks.json, Makefile, README.md, cli.sh, packages/api/.air.toml, packages/api/.gitignore, packages/api/.vscode/tasks.json, packages/api/configs/env.go, packages/api/reload.sh
In this PR:
* Added hot reloading using AIR so that backenders wont have to restart the api everytime they make changes. 
* Added a static bearer token for offline environments
=> Add hot reloading for go api

packages/api/controllers/hackathon_team_controller.go, packages/api/models/hackathon_team_model.go, packages/api/routes/hackathon_team_route.go, packages/api/tests/hackathon_teams_test.go
Jesus I hope it works *fingers crossed*
=> display hackaton teams fixed

packages/web/src/components/spa/HackAUBG/AboutHackathon/AboutHackathon.jsx, packages/web/src/components/spa/HackAUBG/FaqSection/FaqSection.jsx, packages/web/src/components/spa/HackAUBG/GradingCriteria/GradingCriteria.jsx, packages/web/src/components/spa/HackAUBG/JudgesSection/JudgesSection.jsx, packages/web/src/components/spa/HackAUBG/MentorsSection/MentorsSection.jsx, packages/web/src/components/spa/HackAUBG/MentorsSection/mentors_section.css, packages/web/src/components/spa/HackAUBG/ScheduleSection/ScheduleSection.jsx
Added a text saying "Mentors coming soon..."
=> #324 Mentors and Judges coming soon

packages/web/src/components/spa/HackAUBG/HackAUBG.jsx, packages/web/src/components/spa/HackAUBG/hack_aubg.css
Made the scrollbar thumb color green with the background color black.
=> #328 Added new scrollbar design

packages/api/controllers/hackathon_team_controller.go
- Removed the check for a team with no members. Now the api accepts empty teams.
- Added authorization checks in the controller
=> #343 hackathon teams endpoint

packages/web/src/components/admin_page/landing_admin_page.jsx
Made the admin panel login page submit on enter
=> #340 Make the admin panel login form submit when Enter is pressed

packages/web/src/Global.js, packages/web/src/components/other/NotFound.jsx, packages/web/src/components/spa/HackAUBG/ScheduleSection/ScheduleSection.jsx, packages/web/src/components/spa/HackAUBG/ScheduleSection/schedule_section.css, packages/web/src/components/spa/HackAUBG/hack_aubg.css
=> #314 fixed spacing of text containers

packages/api/controllers/hackathon_no_team_participants_controller.go, packages/api/controllers/hackathon_register_controller.go, packages/api/controllers/hackathon_team_members_controller.go, packages/api/models/hackathon_team_member_model.go, packages/api/tests/hackathon_teams_test.go
#357 Fix hackathon participants struct field names (json keys) to match with ones from frontend
=> Fix hackathon participants struct field names

packages/web/src/components/spa/HackAUBG/FaqSection/faq_section.css, packages/web/src/components/spa/HackAUBG/GradingCriteria/grading_criteria.css, packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/journey_desktop.css, packages/web/src/components/spa/HackAUBG/JudgesSection/judges_section.css, packages/web/src/components/spa/HackAUBG/MentorsSection/mentors_section.css, packages/web/src/components/spa/HackAUBG/ScheduleSection/schedule_section.css, packages/web/src/components/spa/HackAUBG/VideoSection/video_section.css
#247  Fixed all headers for HackAUBG in both desktop and mobile. Additionally, here I also fixed the responsiveness issue we had for the schedule section in galaxy fold.
=> #247 headers font size

packages/web/src/components/spa/HackAUBG/hack_aubg.css
Removed horizontal scrollbar in HackAUBG
=> 373 width scrolling

packages/api/controllers/hackathon_register_controller.go
Add return statement when max # of teams is reached
Move CheckIfNoTeamParticiapntExists at the initial stage
=> #380 Fix unhandled case when max number of teams in the hackathon is reached (reg endpoint)

packages/api/models/hackathon_team_member_model.go
=> #376 Remove required tag from TeamName field in TeamMember struct 

packages/api/controllers/hackathon_no_team_participants_controller.go, packages/api/controllers/hackathon_register_controller.go
Fix #383 
There are currently more than 120 documents in the DB.
=> #383 Fix counting of hackathon participants

packages/web/src/components/spa/JobsSection/jobs_section.css
=> #356 fix jobs section button spacing

packages/web/src/components/spa/HackAUBG/FaqSection/FaqSection.jsx, packages/web/src/components/spa/HackAUBG/GradingCriteria/GradingCriteria.jsx, packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/JourneyDesktop.jsx, packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/journey_desktop.css, packages/web/src/components/spa/HackAUBG/JourneySection/JourneyMobile/JourneyMobile.jsx, packages/web/src/components/spa/JobsSection/JobsSection.jsx
Changed grading criteria text and fixed a few font-size and text issues
=> 379 update grading criteria

packages/api/controllers/hackathon_register_controller.go, packages/api/routes/hackathon_register_route.go
Fix #385 
Check if the number of participants is >= 90
if true -> returns 409 status code
if false -> returns 200 status code
=> #385 Create endpoint for checking if reg is avaliable

Makefile, README.md, install_osx.sh, install_wsl.sh, packages/web/src/components/spa/MembersSection/MembersCard.jsx
Added ***GitLens, Auto Rename Tag, Go, and GoTestExplorer*** extensions to ***install-code-plugins phony***
=> #278 Add plugins to Makefile

packages/api/controllers/hackathon_register_controller.go
=> #397 Add missed 503 status codes

packages/web/src/App.js, packages/web/src/components/spa/JobsSection/JobsSection.jsx, packages/web/src/components/spa/MainPage.jsx, packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx, packages/web/src/components/spa/Navigation/DesktopNav/desktop_navbar.css, packages/web/src/components/spa/Navigation/MobileNav/NavMobile.jsx, packages/web/src/components/spa/Navigation/NavFactory.js, packages/web/src/feature_switches.js
Feature switch for disabling components/endpoints. As of now it disables only the Jobs page as it is unfinished.
=> Add a feature switch for disabling components and endpoints 

packages/web/src/App.js, packages/web/src/Global.js, packages/web/src/components/spa/HackAUBG/HackAUBG.jsx
Since there is no time and it's the same as the previous website, a custom scrolling wasn't implemented. Rather, a background colour was added to the HubAUBG body, so there's no white boxes popping around.
=> #394 Add body background colour

cli.sh
Fixed Client menu for Client(prod) and Client(dev)
=> #419 fixed make gum in Client(prod)

Makefile, README.md, install_osx.sh, install_wsl.sh, packages/services/README.md
=> #428 add pyenv and readme for cloud functions

packages/api/tests/TESTS_README.md, packages/api/tests/integration_test.go, packages/api/tests/utils.go
=> #421 disable tests when env is not set correctly and link global env

packages/web/src/Global.js
=> #422 add better handling for port assigning when env url is not provided

packages/services/url_shortener/src/main.rs
=> #432 Add authorization handling in shortener

packages/web/src/components/admin_page/admin.css, packages/web/src/components/spa/JobsSection/JobsCard.jsx, packages/web/src/feature_switches.js
Enabled jobs section and disabled the registration form. Closes #441
=> #441 enable jobs section and disable reg form

packages/api/configs/cron.go
=> #430 Fix security token not being rotated

cli.sh
Added a conditional statement for `make gum` to work with the new name of the repository
=> #454 Fix make gum to work with new repo name

Makefile
Run the phony `make install-python`. 
Verify poetry is installed by running `poetry --version`
=> #466 Update python phony to install poetry package manager

.husky/pre-commit, Makefile, packages/py-api/.pre-commit-config.yaml, packages/py-api/README.md, packages/py-api/mypy.ini, packages/py-api/poetry.lock, packages/py-api/py_api/main.py, packages/py-api/py_api/middleware/auth.py, packages/py-api/py_api/routes/routes.py, packages/py-api/py_api/routes/utility.py, packages/py-api/pyproject.toml
How to verify:
* Make sure you've installed all the latest poetry dependencies - `poetry install` in pi-api directory
* Add some changes to a python file, for example whitelines.
* Commit the changes and the pre-commit hook should fail and remove the whitelines
resolves #472
=> #472 Add python pre-commit hooks

.vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, Makefile, cli.sh, packages/api/.vscode/launch.json, packages/py-api/py_api/main.py
* Run the launcher. Add a breakpoint, hit endpoint. See if stops on breakpoint. 
resolves #473
=> #473 Set up debugging launcher for python api

set_vm_env.sh
=> #456 Add echo command explaining the new global env approach

.github/CODEOWNERS, Makefile, packages/py-api/poetry.lock, packages/py-api/py_api/database/__init__.py, packages/py-api/py_api/database/initialize.py, packages/py-api/py_api/main.py, packages/py-api/py_api/middleware/auth.py, packages/py-api/pyproject.toml
=> #476 Set up mongo connection

packages/web/src/App.js, packages/web/src/Global.js, packages/web/src/components/admin_page/landingEntries.json, packages/web/src/components/admin_page/url_shortener/row.jsx, packages/web/src/components/admin_page/url_shortener/table.jsx, packages/web/src/components/admin_page/url_shortener/url_shortener.jsx, packages/web/src/index.js
Added a new admin panel section for the URL shortener. 
Similarly to what https://bit.ly is, we have our own shortener. 
For example try accessing https://thehub-aubg.com/s/mono - it will lead you to our repo.
* Try to create a new shortened url - with and without a proper URL
* Try to update a shortened url - with and without a proper URL
* Try to remove a shortened url
resolves #436
=> #436 Add admin panel section for url shortener

packages/py-api/py_api/controllers/logs_controller.py, packages/py-api/py_api/controllers/uploader_controller.py, packages/py-api/py_api/middleware/auth.py, packages/py-api/py_api/routes/logs_routes.py, packages/py-api/py_api/routes/routes.py, packages/py-api/py_api/services/mailer.py
* Encapsulated all constants in their representative classes and made them private. Also added @classmethod  where needed.
* Swaped print for a logger in mailer.py
Resolves #496 
Review my code and test the mailer service when an exception is raised.
=> #496 Encapsulate contants and add @classmethod where needed

packages/services/questionnaire/src/lib/inputs/input.svelte, packages/services/questionnaire/src/routes/[department]/+page.svelte
Reverts AUBGTheHUB/monolith#516
=> Revert "#510 Fix inputs not saving state between renders"

docker-compose.yml, packages/services/questionnaire/Dockerfile, packages/services/questionnaire/package-lock.json, packages/services/questionnaire/package.json, packages/services/questionnaire/server.js, packages/services/questionnaire/vite.config.ts, packages/web/nginx.conf
Fixed ssl certificates issue and incorrect proxying for static build files
=> #487 Fix SSL certificates issue with node server and incorrect static files proxying on nginx

.env.sample, packages/py-api/py_api/environment.py, packages/py-api/py_api/main.py, packages/py-api/py_api/middleware/analytics.py, packages/py-api/py_api/middleware/auth.py, packages/py-api/py_api/utilities/logging.py
Fixes the logging issue in deployed environments by using the module level loggers.
resolves #533
=> #533 Add module level logger

packages/services/questionnaire/src/app.html, packages/services/questionnaire/src/lib/inputs/input.svelte
Disabled zooming in when on focus on mobile device and fixed code text to be scrollable on mobile
resolves #537
=> #537 bug mobile zoom on input click and image sizing

packages/services/questionnaire/src/lib/inputs/input.svelte, packages/services/questionnaire/src/routes/questionnaires/[department]/+page.svelte
Fixed responsive by changing the font size and spacing between the dots
=> Fix Stepper Responsive breaking when there are a lot of questions

packages/web/src/components/admin_page/feature_switch_page/row_switch.jsx
=> Fix Feature Switches Popover Not Being Rendered Correctly

packages/py-api/py_api/utilities/logging.py
=> #549 Add date to prod logger

packages/web/src/components/admin_page/feature_switch_page/render_switch.jsx, packages/web/src/components/admin_page/feature_switch_page/row_switch.jsx, packages/web/src/components/admin_page/url_shortener/row.jsx, packages/web/src/components/admin_page/url_shortener/table.jsx
Fixed the issue with edit and delete functionalities on the feature switches. Moved the functions nested inside the components outside for the feature switches and url shortener.
resolves #556
=> #556 move functions from admin panel

deployment.sh
We have to see when this is merged
=> Fix shortener url

packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx
=> test commit

packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx
Reverts AUBGTheHUB/monolith#581
=> Revert "test commit"

packages/py-api/py_api/controllers/hackathon_participants_controller.py, packages/py-api/py_api/routes/hackathon_participants_routes.py
Created a function that deletes the participant from the list of team_names in teams database
resolves #590
=> 590 delete participant

deployment.sh
#584 updates deployment messages
Formats the deployment messages for the discord server in such a way that shows the development environment, last commit URL, and whether the build is successful or not. If the build is not successful, it will display the respective error.
=> #584 updates deployment messages

packages/web/src/components/spa/Navigation/DesktopNav/NavDesktop.jsx, packages/web/src/components/spa/Navigation/DesktopNav/desktop_navbar.css
#636 
Added filler div to keep navigation centered
=> Fix navigation centering in HackAUBG page 

packages/py-api/py_api/functionality/hackathon/participants_base.py, packages/py-api/py_api/models/hackathon_participants_models.py
Added the new fields to the Pydantic model along with the respective validation like specified.
Changed the update_participant() function from the participant_base file so that it can update booleans from false->true and vice-versa. 
Changed the return statement so that it returns the updated participant because previously it was returning the before changes. 
resolves #635
=> #635 Adds new fields to the pydantic participant model

packages/py-api/py_api/controllers/hackathon/participants_controller.py, packages/py-api/py_api/environment.py, packages/py-api/py_api/functionality/hackathon/jwt_base.py, packages/py-api/py_api/functionality/hackathon/participants_base.py
* Added frontend-URLs
* Removed redundant update participant 
* Moved `remove_participant_from_team` func to participants_base.py
=> Added urls for frontend and some minor optimizations to registration workflow

packages/py-api/py_api/controllers/hackathon/participants_controller.py, packages/py-api/py_api/controllers/hackathon/verification_controller.py, packages/py-api/py_api/environment.py, packages/py-api/py_api/functionality/hackathon/jwt_base.py
Changes made:
* Updated urls for frontend
* Update logic for domain depending on evn
=> Update urls and check for env

packages/web/src/components/spa/HackAUBG/FAQSection/data.json
Updated the text in the FAQ section
resolves #651
=> 651-FAQ-text

packages/web/src/components/spa/AboutSection/about_section.css, packages/web/src/components/spa/Footer/footer.css, packages/web/src/components/spa/HackAUBG/AboutHackathon/AboutHackathon.jsx, packages/web/src/components/spa/HackAUBG/AboutHackathon/about_hackathon.css, packages/web/src/components/spa/HackAUBG/AboutHackathon/about_hackathon.module.css, packages/web/src/components/spa/HackAUBG/AwardsSection/awards_section.css, packages/web/src/components/spa/HackAUBG/FAQSection/faq.module.css, packages/web/src/components/spa/HackAUBG/FAQSection/faq_section.module.css, packages/web/src/components/spa/HackAUBG/GradingCriteria/garding_criteria.module.css, packages/web/src/components/spa/HackAUBG/JourneySection/JourneyDesktop/journey_desktop.css, packages/web/src/components/spa/HackAUBG/JourneySection/JourneyMobile/journey_mobile.css, packages/web/src/components/spa/HackAUBG/ScheduleSection/schedule_section.css, packages/web/src/components/spa/HackAUBG/VideoSection/video_section.css
#660 
Rework schedule and awards sections and change all titles font -sizes
=> 660 Rework schedule and awards sections and change all titles font -sizes

packages/web/src/components/spa/HackAUBG/FAQSection/faq_section.module.css, packages/web/src/components/spa/HackAUBG/MentorsSection/MentorsSection.jsx, packages/web/src/components/spa/HackAUBG/SponsorsSection/SponsorsSection.jsx, packages/web/src/components/spa/HackAUBG/SponsorsSection/sponsors_section.css
Reworked Sponsors Section colors and fonts to match the theme of the website
=> #667 Rework Sponsors Section

deployment.sh
Update deployment.sh to use the docker compose from docker engine
=> Replaced docker-compose apt package command with docker compose command from docker engine

packages/py-api/py_api/functionality/hackathon/mailing_functionality.py
Changed Css value from initial to block for email template
=> Fix Email text not centered

packages/web/src/components/spa/HackAUBG/JudgesSection/JudgesSection.jsx, packages/web/src/components/spa/HackAUBG/JudgesSection/judges_section.module.css, packages/web/src/components/spa/HackAUBG/MentorsSection/MentorsSection.jsx, packages/web/src/components/spa/HackAUBG/MentorsSection/mentors_section.module.css
Fixed Mentors and Judges coming soon text to fit the rest of the coming soon tags
=> Mentors Judges coming soon fixes

packages/py-api/py_api/models/hackathon_participants_models.py, packages/py-api/resources/email_templates/email-participant.html, packages/web/src/components/spa/HackAUBG/RegistrationForm/RegistrationForm.jsx
- Fix min age in py-api
- Added check for inviteLink to disappear when invited person joins\
- Modification to models
- Added check if verify is present in url to not show which team you are registering for
=> Fixes on Emails and Models

deployment.sh
I changed how the content string is built so that it solves the issue of weird indentation. I resolved a syntax error, which was preventing the error message to be shown in the cases of a build failure. 
resolves #584
=> #584 Fix bug with pipeline discord messages

packages/py-api/py_api/controllers/hackathon/participants_controller.py, packages/web/src/components/admin_page/hackathon/hackathon_teams/hackathon_teams.jsx
Changed the max team capacity to 17 and fix csv to xlsx
=> Change max team capacity

packages/web/src/components/spa/HackAUBG/SponsorsSection/SponsorsSection.jsx, packages/web/src/components/spa/HackAUBG/SponsorsSection/sponsors_section.css
Added the media sponsors to the section. Uploaded the current ones to the admin panel and they are being rendered.
Fixes issue #692 
- Run all three APIs (Python, Go, React)
- Go to the sponsors section
=> Added Media sponsors to sponsors section

packages/web/src/AdminRoutesWithBackButton.js
Add member page was missing from AdminRoutesWith backbtn so i added it
=> Add member page missing from admin panel

services/py-api/pyproject.toml, services/py-api/pytest.ini, services/py-api/src/database/transaction_manager.py, services/py-api/src/server/schemas/response_schemas/schemas.py, services/py-api/tests/conftest.py, services/py-api/tests/unit_tests/README.md, services/py-api/tests/unit_tests/test_db_manager.py, services/py-api/tests/unit_tests/test_trancation_manager.py
I have written more comprehensive tests for the DatabaseManager and some unit tests for the `TransactionManager`
=> Write tests for db layer

README.md, wsl_ssh_forwarding.sh
The fix is documented by Micosoft in this link https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials
=> Explain how to solve missing SSH keys error in WSL

.gitignore, services/py-api/src/server/logger/logger_factory.py
=> #770 Rotation of files not working properly

services/web/package-lock.json, services/web/package.json, services/web/tsconfig.json
Install react hook form and zod
Also enabled strict mode in tsconfig.json
resolves #775 
=> #775 install react hook form and zod

services/py-api/src/server/handlers/hackathon_handlers.py, services/py-api/src/server/handlers/participants_handlers.py, services/py-api/tests/integration_tests/conftest.py, services/py-api/tests/integration_tests/test_participant_routes.py, services/py-api/tests/integration_tests/test_team_routes.py, services/py-api/tests/unit_tests/conftest.py, services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py, services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py, services/py-api/tests/unit_tests/test_handlers/test_hackathon_handlers.py, services/py-api/tests/unit_tests/test_handlers/test_participant_handlers.py
#824 Write Unit and Integration Tests for Delete Endpoints
resolves #824
=> #824 Write Unit and Integration Tests for Delete Endpoints

.github/CODEOWNERS
=> Deprecate @asynchroza aka Toni, owner of the club

.github/workflows/pipeline.yml
=> Remove building the services conditionally

services/web/src/website/MainPage/Footer/Footer.tsx
#872 Footer email
made the paragraph an anchor, changed the email and added opening of mail client
resolves #872
=> #872 open mail client

services/web/src/components/ui/sheet.tsx
#873 fixed issue where x on mobile menu had a box around it by default
resolves #873
=> fixed issue with border on x

services/web/src/website/MainPage/LandingSection/LandingSection.tsx
#874 
Made the circuit effect smaller when hovering the mouse. 
Also, now when the mouse leaves the blue section of the page the effect disappears (before it stayed in the place where mouse was the last time.)
Additionally, tweaked some margins.
=> Fixes 874: Make circuit effect smaller, make it disappear when leaving the section of the page and tweak the margins

services/web/src/website/MainPage/LandingSection/LandingSection.tsx
#894  Fix Mobile Circuit Board (#894 )
=> 894  Fix Mobile Circuit Board

services/py-api/src/database/repository/feature_switch_repository.py, services/py-api/src/server/handlers/feature_switch_handler.py, services/py-api/src/server/routes/utility_routes.py, services/py-api/src/server/schemas/response_schemas/schemas.py, services/py-api/src/service/feature_switch_service.py
Write the logic for retrieving all feature switches
=> implement fetch all feature switches

.github/workflows/pipeline.yml, services/web/Dockerfile
=> try secrets for build time

services/web/src/website/HackathonPage/Navigation/DesktopNav.tsx, services/web/src/website/HackathonPage/Navigation/MobileNav.tsx, services/web/src/website/HackathonPage/ScheduleSection/ScheduleSection.tsx
Now this PR is fine not like the previous one.
=> Adjustments to the navigations

services/web/src/website/HackathonPage/FAQSection/HackathonFAQ.tsx, services/web/src/website/HackathonPage/HackathonPage.tsx
#934 implement FAQ section
- Simple FAQ section that matches the Figma Design. 
- Keeps only one question open closing the previously opened ones
- Has an transition when opening the question
- its responsive
resolves #934
=> #934 implement FAQ section

services/web/src/components/EmblaCarousel/SlidesPerViewCarousel/css/embla.css
Based on this discussion: https://github.com/davidjerleke/embla-carousel/issues/890
=> fix carousel animation stuttering for Iphone

.github/workflows/dev_deploy.yml, services/py-api/Dockerfile
Since our servers are now behind the Cloudflare proxy we cannot resolve their IP address using the domain. For this reason the deploy action failed. After consulting this with the maintainer of the action, changing the host to the IP address of the vps works perfectly fine without any drawbacks or consequences.
=> deploy the stack using the ip of the vps

services/py-api/src/database/model/participant_model.py, services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx, services/web/src/website/RegistrationFormPage/RegistrationForm/constants.ts
#967 Make Registration Form Wider and Add missing options
Made registration form wider and added missing "Social media" option
resolves #967
=> 967 Make Registration Form Wider and Add Missing Options

package-lock.json, package.json, services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx
#970  Add Smoothness Animation On The Registration Page
Added the smoothness animation on the registration form page as well.
resolves #970
=> Add Smoothness Animation On The Registration Page

services/web/src/website/HackathonPage/NavigationSection/MobileNav.tsx
Reworked HackAubg Navigation Z-index so that it does not go over the hamburger menu
=> #979 Rework HackAubg Navigation Z-index

services/web/src/constants.ts, services/web/src/website/HackathonPage/NavigationSection/DesktopNav.tsx, services/web/src/website/HackathonPage/RecapSection/Recap.tsx, services/web/src/website/RegistrationFormPage/NavigationSection/MobileNav.tsx, services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx, services/web/src/website/RegistrationFormPage/RegistrationForm/schema.ts
What has been fixed: 
- About button on HackAubg page was not working
- Navbar did not have background on the RegPage
- Whitelist dashes for name input field
- Add date check so that we have appropriate messages for when the registration form is not open
- Add new video
=> Fixing Front end nits

services/py-api/src/database/model/participant_model.py, services/web/src/website/RegistrationFormPage/RegistrationForm/constants.ts
#978  Remove XS T-shirt option
Removed XS T-shirt option from the registration form and the backend.
=> Remove XS T-shirt option

services/web/src/website/MainPage/MeetTheTeamSection/components/HubberModule.tsx
The cards for each member are shown only after the image is fully loaded.
=> set a loading state to the team members carousel

.github/workflows/prod_deploy.yml, services/web/prod.Dockerfile
Updated and configured the prod VPS to make it ready for deployment
=> update production deployment scripts

services/py-api/src/service/hackathon_service.py, services/py-api/src/service/mail_service/email_templates/email-registration-confirmation.html, services/py-api/src/service/mail_service/email_templates/email-verify-participant.html, services/py-api/src/service/mail_service/utils.py, services/react-email-starter/emails/verification-email.tsx, services/react-email-starter/emails/welcome-email.tsx, services/react-email-starter/out/verification-email.html, services/react-email-starter/out/welcome-email.html, services/web/src/website/RegistrationFormPage/RegistrationForm/RegistrationForm.tsx
Fixing email client styling issues
=> Fixed styling issues in all clients

services/py-api/src/database/model/participant_model.py, services/py-api/src/server/schemas/request_schemas/schemas.py, services/py-api/src/service/hackathon_service.py
Sets the length constraints of the participant fields to match the frontend.
=> set length constraints to the participant fields

services/web/src/website/HackathonPage/GradingSection/GradingSection.tsx
Update the grading criteria to reflect the criteria set for HackAUBG 7.0
=> update the grading criteria

services/web/src/website/HackathonPage/CarouselComponents/components/JurySection/components/JurySection.tsx, services/web/src/website/HackathonPage/CarouselComponents/components/MentorsSection/components/MentorsSection.tsx, services/web/src/website/HackathonPage/SponsorsSection/HackathonSponsors.tsx, services/web/src/website/MainPage/HackAUBGSection/HackAUBGSection.tsx
This should stay like this until the Mongo Connectivity issues for the prod machine are resolved.
=> display jury, mentors and sponsors by default

services/web/src/website/HackathonPage/CarouselComponents/components/JurySection/components/JurySection.tsx, services/web/src/website/HackathonPage/CarouselComponents/components/MentorsSection/components/MentorsSection.tsx, services/web/src/website/HackathonPage/SponsorsSection/HackathonSponsors.tsx, services/web/src/website/MainPage/HackAUBGSection/HackAUBGSection.tsx
Reverts AUBGTheHUB/monolith#1006
@Isak-Bego approve when Contabo is fixed
=> Revert "display jury, mentors and sponsors by default"

.github/workflows/dev_deploy_new.yml, docker-swarm-stack.yml
=> New cd pipeline

.github/workflows/dev_manifest_based_deploy.yml, deployment-manifest.yml
Fixes #1010 
This should be tested and merged after https://github.com/AUBGTheHUB/monolith/pull/1012
=> Manual deployment with manifest file

.github/workflows/pytests.yml, services/py-api/tests/integration_tests/conftest.py, services/py-api/tests/integration_tests/test_jwt_utility.py, services/py-api/tests/integration_tests/test_participant_routes.py, services/py-api/tests/integration_tests/test_team_routes.py, services/py-api/tests/integration_tests/test_utility_routes.py, services/py-api/tests/integration_tests/test_verification_routes.py, services/py-api/tests/unit_tests/conftest.py, services/py-api/tests/unit_tests/test_database_layer/test_db_manager.py, services/py-api/tests/unit_tests/test_database_layer/test_model_serialization.py, services/py-api/tests/unit_tests/test_database_layer/test_participant_repository.py, services/py-api/tests/unit_tests/test_database_layer/test_team_repository.py, services/py-api/tests/unit_tests/test_database_layer/test_trancation_manager.py, services/py-api/tests/unit_tests/test_handlers/test_hackathon_handlers.py, services/py-api/tests/unit_tests/test_handlers/test_participant_handlers.py, services/py-api/tests/unit_tests/test_handlers/test_utility_handlers.py, services/py-api/tests/unit_tests/test_handlers/test_verification_handlers.py, services/py-api/tests/unit_tests/test_service_layer/test_hackathon_service.py, services/py-api/tests/unit_tests/test_service_layer/test_participant_registration_service.py, services/py-api/tests/unit_tests/test_service_layer/test_participants_verification_service.py
=> fix: rewrite the unit & integration tests for the new backend structure

docker-swarm-stack.yml, services/py-api/Dockerfile
=> Fix py api dockerfile

.github/workflows/dev_deploy.yml
=> remove main branch check
